apiVersion: apps/v1
kind: Deployment
metadata:
  name: volunteer-service
  namespace: volunteer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volunteer-service
  template:
    metadata:
      labels:
        app: volunteer-service
    spec:
      containers:
        - name: volunteer-service
          image: 451638006344.dkr.ecr.us-east-1.amazonaws.com/volunteer-service:v1.0.2
          ports:
            - containerPort: 8082
              name: http
          env:
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: volunteer-service-config
                  key: AWS_REGION
            - name: AWS_DYNAMODB_TABLE
              valueFrom:
                configMapKeyRef:
                  name: volunteer-service-config
                  key: AWS_DYNAMODB_TABLE
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"