apiVersion: v1
kind: Secret
metadata:
  name: volunteer-service-secrets
  namespace: volunteer-service
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:postgres@volunteer-db.c69c2yweoc4n.us-east-1.rds.amazonaws.com:5432/volunteer_db"